//Auth Types
export const LOAD = "LOAD";

export const REGISTER_MSG = "REGISTER_MSG";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const VERIFY_FAIL = "VERIFY_FAIL";

export const FORGET_MSG = "FORGET_MSG";
export const FORGET_SUCCESS = "FORGET_SUCCESS";
export const FORGET_FAIL = "FORGET_FAIL";
export const RESET_SUCCESS = "RESET_SUCCESS";
export const RESET_FAIL = "RESET_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_MSG = "LOGIN_MSG";
export const LOGIN_MSG_ERR = "LOGIN_MSG_ERR";

export const SET_AUTH_VERIFICATION = "SET_AUTH_VERIFICATION";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const ERR_USERS = "ERR_USERS";

export const LOGOUT = "LOGOUT";

export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_ERR = "UPDATE_PASSWORD_ERR";

export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_ERR = "UPDATE_PROFILE_ERR";

export const IS_EMAIL_AUTH_ON_SUCCESS = "IS_EMAIL_AUTH_ON_SUCCESS";
export const IS_EMAIL_AUTH_ON_ERR = "IS_EMAIL_AUTH_ON_ERR";

export const IS_GOOGLE_AUTH_ON_SUCCESS = "IS_GOOGLE_AUTH_ON_SUCCESS";
export const IS_GOOGLE_AUTH_ON_ERR = "IS_GOOGLE_AUTH_ON_ERR";

export const IS_SMS_AUTH_ON_SUCCESS = "IS_SMS_AUTH_ON_SUCCESS";
export const IS_SMS_AUTH_ON_ERR = "IS_SMS_AUTH_ON_ERR";

//Dashboard Types
export const ALL_ELECTIONS_COUNT_SUCCESS = "ALL_ELECTIONS_COUNT_SUCCESS";
export const ALL_ELECTIONS_COUNT_ERR = "ALL_ELECTIONS_COUNT_ERR";
export const ALL_USERS_COUNT_SUCCESS = "ALL_USERS_COUNT_SUCCESS";
export const ALL_USERS_COUNT_ERR = "ALL_USERS_COUNT_ERR";
export const ALL_ORDERS_COUNT_SUCCESS = "ALL_ORDERS_COUNT_SUCCESS";
export const ALL_ORDERS_COUNT_ERR = "ALL_ORDERS_COUNT_ERR";
export const ALL_TOKENS_COUNT_SUCCESS = "ALL_TOKENS_COUNT_SUCCESS";
export const ALL_TOKENS_COUNT_ERR = "ALL_TOKENS_COUNT_ERR";

export const INVESTMENT_PER_MONTH_SUCCESS = "INVESTMENT_PER_MONTH_SUCCESS";
export const INVESTMENT_PER_MONTH_ERR = "INVESTMENT_PER_MONTH_ERR";
export const USERS_PER_MONTH_SUCCESS = "USERS_PER_MONTH_SUCCESS";
export const USERS_PER_MONTH_ERR = "USERS_PER_MONTH_ERR";
export const ORDERS_PER_DAY_SUCCESS = "ORDERS_PER_DAY_SUCCESS";
export const ORDERS_PER_DAY_ERR = "ORDERS_PER_DAY_ERR";
export const GET_USER_COUNT = "GET_USER_COUNT";
export const ORDERS_COUNT = "ORDERS_COUNT";
export const EXCHANGE_SELL_ORDER = "EXCHANGE_SELL_ORDER";
export const EXCHANGE_BUY_ORDER = "EXCHANGE_BUY_ORDER";

// User Management Types
export const GET_USERS_LIST_SUCCESS = "GET_USERS_LIST_SUCCESS";
export const GET_USERS_LIST_ERR = "GET_USERS_LIST_ERR";

export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_ERR = "GET_USER_PROFILE_ERR";

export const GET_INVESTMENT_DETAIL_SUCCESS = "GET_INVESTMENT_DETAIL_SUCCESS";
export const GET_INVESTMENT_DETAIL_ERR = "GET_INVESTMENT_DETAIL_ERR";

export const BLOCK_UNBLOCK_SUCCESS = "BLOCK_UNBLOCK_SUCCESS";
export const BLOCK_UNBLOCK_ERR = "BLOCK_UNBLOCK_ERR";

//Wallet Types
export const DEPOSIT_PAYMENT_SUCCESS = "DEPOSIT_PAYMENT_SUCCESS";
export const DEPOSIT_PAYMENT_ERR = "DEPOSIT_PAYMENT_ERR";

export const GET_WALLET_DETAILS_SUCCESS = "GET_WALLET_DETAILS_SUCCESS";
export const GET_WALLET_DETAILS_ERR = "GET_WALLET_DETAILS_ERR";

// content Management Types
export const UPDATE_HOME_PAGE_SUCCESS = "UPDATE_HOME_PAGE_SUCCESS";
export const UPDATE_HOME_PAGE_ERR = "UPDATE_HOME_PAGE_ERR";

export const UPDATE_ABOUT_PAGE_SUCCESS = "UPDATE_ABOUT_PAGE_SUCCESS";
export const UPDATE_ABOUT_PAGE_ERR = "UPDATE_ABOUT_PAGE_ERR";

export const UPDATE_CONTACT_PAGE_SUCCESS = "UPDATE_CONTACT_PAGE_SUCCESS";
export const UPDATE_CONTACT_PAGE_ERR = "UPDATE_CONTACT_PAGE_ERR";

// Kyc Management Types
export const SINGLE_APPROVED_KYC_SUCCESS = "SINGLE_APPROVED_KYC_SUCCESS";
export const SINGLE_APPROVED_KYC_ERR = "SINGLE_APPROVED_KYC_ERR";
export const GET_TOKEN_LIST_SUCCESS = "GET_TOKEN_LIST_SUCCESS";
export const GET_TOKEN_LIST_ERR = "GET_TOKEN_LIST_ERR";

export const PENDING_KYC_SUCCESS = "PENDING_KYC_SUCCESS";
export const PENDING_KYC_ERR = "PENDING_KYC_ERR";
export const APPROVED_KYC_SUCCESS = "APPROVED_KYC_SUCCESS";
export const APPROVED_KYC_ERR = "APPROVED_KYC_ERR";
export const REJECTED_KYC_SUCCESS = "REJECTED_KYC_SUCCESS";
export const REJECTED_KYC_ERR = "REJECTED_KYC_ERR";

export const GET_KYC_SUCCESS = "GET_KYC_SUCCESS";
export const GET_KYC_ERR = "GET_KYC_ERR";

export const KYC_UPDATE_SUCCESS = "KYC_UPDATE_SUCCESS";
export const KYC_UPDATE_ERR = "KYC_UPDATE_ERR";

//Exhange Types
export const CREATE_TOKENS_SUCCESS = "CREATE_TOKENS_SUCCESS";
export const CREATE_TOKENS_ERR = "CREATE_TOKENS_ERR";

export const GET_TOKENS_SUCCESS = "GET_TOKENS_SUCCESS";
export const GET_TOKENS_ERR = "GET_TOKENS_ERR";
export const TOKEN_ADDED_EXCHANGE_SUCCESS = "TOKEN_ADDED_EXCHANGE_SUCCESS";
export const TOKEN_ADDED_EXCHANGE_ERR = "TOKEN_ADDED_EXCHANGE_ERR";

export const GET_UNHOLD_TOKENS_SUCCESS = "GET_UNHOLD_TOKENS_SUCCESS";
export const GET_UNHOLD_TOKENS_ERR = "GET_UNHOLD_TOKENS_ERR";
export const GET_ONHOLD_TOKENS_SUCCESS = "GET_ONHOLD_TOKENS_SUCCESS";
export const GET_ONHOLD_TOKENS_ERR = "GET_ONHOLD_TOKENS_ERR";

export const TOKEN_UNBLOCKED_SUCCESS = "TOKEN_UNBLOCKED_SUCCESS";
export const TOKEN_UNBLOCKED_ERR = "TOKEN_UNBLOCKED_ERR";
export const TOKEN_BLOCKED_SUCCESS = "TOKEN_BLOCKED_SUCCESS";
export const TOKEN_BLOCKED_ERR = "TOKEN_BLOCKED_ERR";

export const GET_BUY_REQUEST_LIST_SUCCESS = "GET_BUY_REQUEST_LIST_SUCCESS";
export const GET_BUY_REQUEST_LIST_ERR = "GET_BUY_REQUEST_LIST_ERR";

export const GET_SELL_REQUEST_LIST_SUCCESS = "GET_SELL_REQUEST_LIST_SUCCESS";
export const GET_SELL_REQUEST_LIST_ERR = "GET_SELL_REQUEST_LIST_ERR";

export const GET_COMPLETED_ORDERS_SUCCESS = "GET_COMPLETED_ORDERS_SUCCESS";
export const GET_COMPLETED_ORDERS_ERR = "GET_COMPLETED_ORDERS_ERR";

//Voting Types
export const GET_ALL_ITO_SUCCESS = "GET_ALL_ITO_SUCCESS";
export const GET_ALL_ITO_ERR = "GET_ALL_ITO_ERR";

export const GET_ONGOING_VOTING_SUCCESS = "GET_ONGOING_VOTING_SUCCESS";
export const GET_ONGOING_VOTING_ERR = "GET_ONGOING_VOTING_ERR";

export const GET_UPCOMING_VOTING_SUCCESS = "GET_UPCOMING_VOTING_SUCCESS";
export const GET_UPCOMING_VOTING_ERR = "GET_UPCOMING_VOTING_ERR";

export const GET_CLOSED_VOTING_SUCCESS = "GET_CLOSED_VOTING_SUCCESS";
export const GET_CLOSED_VOTING_ERR = "GET_CLOSED_VOTING_ERR";

export const GET_VOTING_DETAIL_SUCCESS = "GET_VOTING_DETAIL_SUCCESS";
export const GET_VOTING_DETAIL_ERR = "GET_VOTING_DETAIL_ERR";

export const CREATE_VOTE_SUCCESS = "CREATE_VOTE_SUCCESS";
export const CREATE_VOTE_ERR = "CREATE_VOTE_ERR";

export const GET_VOTE_STATUS_SUCCESS = "GET_VOTE_STATUS_SUCCESS";
export const GET_VOTE_STATUS_ERR = "GET_VOTE_STATUS_ERR";

//Ito Management Types
export const CREATE_ITO_SUCCESS = "CREATE_ITO_SUCCESS";
export const CREATE_ITO_ERR = "CREATE_ITO_ERR";

export const UNASSIGNED_ADMINS_SUCCESS = "UNASSIGNED_ADMINS_SUCCESS";
export const UNASSIGNED_ADMINS_ERR = "UNASSIGNED_ADMINS_ERR";
export const ONGOING_ITO_SUCCESS = "ONGOING_ITO_SUCCESS";
export const ONGOING_ITO_ERR = "ONGOING_ITO_ERR";
export const UPCOMING_ITO_SUCCESS = "UPCOMING_ITO_SUCCESS";
export const UPCOMING_ITO_ERR = "UPCOMING_ITO_ERR";
export const PAST_ITO_SUCCESS = "PAST_ITO_SUCCESS";
export const PAST_ITO_ERR = "PAST_ITO_ERR";

export const GET_ITO_SUCCESS = "GET_ITO_SUCCESS";
export const GET_ITO_ERR = "GET_ITO_ERR";

export const UPDATE_ITO_SUCCESS = "UPDATE_ITO_SUCCESS";
export const UPDATE_ITO_ERR = "UPDATE_ITO_ERR";

// admin request

export const GET_DEPOSITES_LIST_SUCCESS = "GET_DEPOSITES_LIST_SUCCESS";
export const GET_DEPOSITES_LIST_ERR = "GET_DEPOSITES_LIST_ERR";

export const GET_ALL_DEPOSITES_LIST_SUCCESS = "GET_ALL_DEPOSITES_LIST_SUCCESS";
export const GET_ALL_DEPOSITES_LIST_ERR = "GET_ALL_DEPOSITES_LIST_ERR";

export const CONFIRM_DEPOSITE_SUCCESS = "CONFIRM_DEPOSITE_SUCCESS";
export const CONFIRM_DEPOSITE_ERR = "CONFIRM_DEPOSITE_ERR";

export const GET_DEPOSITE_BY_ID_SUCCESS = "GET_DEPOSITE_BY_ID_SUCCESS";
export const GET_DEPOSITE_BY_ID_ERR = "GET_DEPOSITE_BY_ID_ERR";

export const GET_SINGLE_APPROVED_SUCCESS = "GET_SINGLE_APPROVED_SUCCESS";
export const GET_SINGLE_APPROVED_ERR = "GET_SINGLE_APPROVED_ERR";

//Admin Management Types
export const GET_ADMIN_LIST_SUCCESS = "GET_ADMIN_LIST_SUCCESS";
export const GET_ADMIN_LIST_ERR = "GET_ADMIN_LIST_ERR";

export const GET_ADMIN_BY_ID_SUCCESS = "GET_ADMIN_BY_ID_SUCCESS";
export const GET_ADMIN_BY_ID_ERR = "GET_ADMIN_BY_ID_ERR";

export const GET_ADMIN_ITO_SUCCESS = "GET_ADMIN_ITO_SUCCESS";
export const GET_ADMIN_ITO_ERR = "GET_ADMIN_ITO_ERR";

export const ADD_NEW_ADMIN_SUCCESS = "ADD_NEW_ADMIN_SUCCESS";
export const ADD_NEW_ADMIN_ERR = "ADD_NEW_ADMIN_ERR";

export const DELETE_ADMIN_SUCCESS = "DELETE_ADMIN_SUCCESS";
export const DELETE_ADMIN_ERR = "DELETE_ADMIN_ERR";

export const ADMIN_BLOCK_UNBLOCK_SUCCESS = "ADMIN_BLOCK_UNBLOCK_SUCCESS";
export const ADMIN_BLOCK_UNBLOCK_ERR = "ADMIN_BLOCK_UNBLOCK_ERR";

export const ADMIN_LINK_ITO_SUCCESS = "ADMIN_LINK_ITO_SUCCESS";
export const ADMIN_LINK_ITO_ERR = "ADMIN_LINK_ITO_ERR";

export const ADMIN_UNLINK_ITO_SUCCESS = "ADMIN_UNLINK_ITO_SUCCESS";
export const ADMIN_UNLINK_ITO_ERR = "ADMIN_UNLINK_ITO_ERR";

export const ALL_ITO_SUCCESS = "ALL_ITO_SUCCESS";
export const ALL_ITO_ERR = "ALL_ITO_ERR";

//Subscription Types
export const CREATE_SUBSCRIPTION_SUCCESS = "CREATE_SUBSCRIPTION_SUCCESS";
export const CREATE_SUBSCRIPTION_ERR = "CREATE_SUBSCRIPTION_ERR";

//Calculator Types
export const GET_ALL_TOKENS_SUCCESS = "GET_ALL_TOKENS_SUCCESS";
export const GET_ALL_TOKENS_ERR = "GET_ALL_TOKENS_ERR";

// Audit Logs
export const GET_AUDIT_LOGS_SUCCESS = "GET_AUDIT_LOGS_SUCCESS";
export const GET_AUDIT_LOGS_ERR = "GET_AUDIT_LOGS_ERR";

//Dinisium Bank Account
export const GET_BANK_ACCOUNT_DETAILS_SUCCESS =
  "GET_BANK_ACCOUNT_DETAILS_SUCCESS";
export const GET_BANK_ACCOUNT_DETAILS_ERR = "GET_BANK_ACCOUNT_DETAILS_ERR";

export const ADD_BANK_ACCOUNT_DETAILS_SUCCESS =
  "ADD_BANK_ACCOUNT_DETAILS_SUCCESS";
export const ADD_BANK_ACCOUNT_DETAILS_ERR = "ADD_BANK_ACCOUNT_DETAILS_ERR";

export const UPDATE_BANK_ACCOUNT_DETAILS_SUCCESS =
  "UPDATE_BANK_ACCOUNT_DETAILS_SUCCESS";
export const UPDATE_BANK_ACCOUNT_DETAILS_ERR =
  "UPDATE_BANK_ACCOUNT_DETAILS_ERR";
