import React, { useState } from "react";
import verificationImg from "../../../../App/Assets/images/verification.png";
import { verifyGoogle } from "../../../../Redux/actions/actions";
import { connect } from "react-redux";
import { useHistory } from "react-router-dom";

const GoogleVerificationForm = ({
  setVerificationPage,
  userId,
  auth,
  verifyGoogle,
}) => {
  const [loading, setLoading] = useState(false);
  let history = useHistory();
  const [verificationCode, setVerificationCode] = useState("");

  const onChange = (e) => {
    setVerificationCode(e.target.value);
  };

  const onSubmit = (e) => {
    e.preventDefault();
    setLoading(true);
    verifyGoogle({ verificationCode, userId, history, setLoading });
    // setVerificationPage({
    //   emailPage: false,
    //   smsPage: false,
    //   googlePage: false,
    // });
  };

  return (
    <form className="form" onSubmit={onSubmit}>
      <h3 className="h3">2-Step Verification</h3>
      <p>
        {" "}
        <img
          src={verificationImg}
          style={{ width: "25px", height: "25px" }}
          alt="..."
        />{" "}
        Enter the Verification code Generated by Google auhtentication
      </p>
      <div className="form-group">
        <label> Code</label>

        <input
          type="text"
          placeholder="Enter Code"
          className="form-control"
          name="verificationCode"
          value={verificationCode}
          onChange={(e) => onChange(e)}
          required
        />
      </div>
      <button
        style={{ marginBottom: "20px" }}
        type="submit"
        className="btn btn-outline-primary"
        disabled={loading}
      >
        {loading && <span className="spinner-border spinner-border-sm"></span>}{" "}
        VERIFY
      </button>
      <div class="alert alert-info" role="alert">
        If you have lost google authentication app, please contact with our
        support. So that you can login to your dashboard.
      </div>
    </form>
  );
};

const mapStateToProps = (state) => ({
  auth: state.auth,
});

export default connect(mapStateToProps, { verifyGoogle })(
  GoogleVerificationForm
);
